set nocompatible

execute pathogen#infect()
syntax on
filetype plugin indent on

" ===== INTERFACE =====
set autoindent
set backspace=indent,eol,start
set cursorline
set hidden
set history=1000
set list
set list listchars=tab:>-,trail:.,extends:>
set nowrap
set number
set ruler
set shell=zsh
set showcmd
set showmode
set wildmenu

" ===== TABBING =====
let s:tab_num=2
set expandtab
set smarttab

" ===== COLOR SCHEME =====
color molokai
set t_Co=256

" ===== CURSOR =====
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" ===== NERDTree =====
autocmd vimenter * NERDTree
map <Leader>t :NERDTreeToggle<cr>
let NERDTreeShowHidden=1

" ===== KEY MAPPING =====
:imap jj <Esc>
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
