set nocompatible
filetype off

" change leader key
let mapleader = ","

" ===== BEGIN VUNDLE SETUP =====
"
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" a Git wrapper so awesome, it should be illegal
Plugin 'tpope/vim-fugitive'
autocmd BufReadPost fugitive://* set bufhidden=delete
Plugin 'idanarye/vim-merginal'
Plugin 'airblade/vim-gitgutter'

" silver search
Plugin 'rking/ag.vim'
nnoremap <leader>a :Ag

" markdown
Plugin 'plasticboy/vim-markdown'

" a tree explorer plugin
Plugin 'scrooloose/nerdtree'

" molokai color scheme
Plugin 'tomasr/molokai'

" commenting
Plugin 'tComment'

" Vim/Ruby configuration files
Plugin 'vim-ruby/vim-ruby'
let ruby_no_expensive=1

" Rails configuration files
Plugin 'tpope/vim-rails'

Plugin 'fatih/vim-go'
let g:go_fmt_command = "goimports"

" All of your Plugins must be added before the following line
call vundle#end()

filetype plugin indent on " file type detection
syntax on                 " syntax highlighting

" ===== INTERFACE SETUP =====
"
set autoindent
set clipboard=unnamed
set colorcolumn=100
set cursorline
set expandtab
set smarttab
set hlsearch
set incsearch
set list
set list listchars=tab:>-,trail:.,extends:>
set noswapfile
set nowrap
set number
set ruler
set showcmd
set so=10
set t_Co=256
set ttyfast

let s:tab_num = 4
let &softtabstop=s:tab_num
let &shiftwidth=s:tab_num
let &tabstop=s:tab_num

" ===== NERDTree SETUP =====
"
" open NERDTree if no file specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

map <leader>n :NERDTreeToggle<cr>
let NERDTreeShowHidden=1
let NERDTreeCascadeSingleChildDir=0


" ===== KEY MAPPING =====
"
" escape shortcut
:imap jj <Esc>

" quick save
nnoremap <leader>m :w <return>

" navigation between split windows
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l


" ===== COLOR SCHEME =====
"
color molokai
